services:
  nginx:
    container_name: nginx
    image: nginx
    build: ./requirements/nginx
    ports:
      - 443:443
    #    depends_on:
    #  - wordpress
    # volumes:
    # - wordpress:/var/www/wordpress
    networks:
      - inception
    restart: always

networks:
  inception:
    name: inception
